export const STARWEET_CREATE_REQUEST = "STARWEET_CREATE_REQUEST";
export const STARWEET_CREATE_SUCCESS = "STARWEET_CREATE_SUCCESS";
export const STARWEET_CREATE_FAILURE = "STARWEET_CREATE_FAILURE";

export const STARWEET_DELETE_REQUEST = "STARWEET_DELETE_REQUEST";
export const STARWEET_DELETE_SUCCESS = "STARWEET_DELETE_SUCCESS";
export const STARWEET_DELETE_FAILURE = "STARWEET_DELETE_FAILURE";

export const GET_ALL_STARWEETS_REQUEST = "SGET_ALL_STARWEETS_REQUEST";
export const GET_ALL_STARWEETS_SUCCESS = "GET_ALL_STARWEETS_SUCCESS";
export const GET_ALL_STARWEETS_FAILURE = "GET_ALL_STARWEETS_FAILURE";

export const GET_USERS_STARWEET_REQUEST = "GET_USERS_STARWEET_REQUEST";
export const GET_USERS_STARWEET_SUCCESS = "GET_USERS_STARWEET_SUCCESS";
export const GET_USERS_STARWEET_FAILURE = "GET_USERS_STARWEET_FAILURE";

export const USER_LIKE_STARWEET_REQUEST = "USER_LIKE_STARWEET_REQUEST";
export const USER_LIKE_STARWEET_SUCCESS = "USER_LIKE_STARWEET_SUCCESS";
export const USER_LIKE_STARWEET_FAILURE = "USER_LIKE_STARWEET_FAILURE";

export const LIKE_STARWEET_REQUEST = "LIKE_STARWEET_REQUEST";
export const LIKE_STARWEET_SUCCESS = "LIKE_STARWEET_SUCCESS";
export const LIKE_STARWEET_FAILURE = "LIKE_STARWEET_FAILURE";

export const FIND_STARWEET_BY_ID_REQUEST = "FIND_STARWEET_BY_ID_REQUEST";
export const FIND_STARWEET_BY_ID__SUCCESS = "FIND_STARWEET_BY_ID_SUCCESS";
export const FIND_STARWEET_BY_ID_FAILURE = "FIND_STARWEET_BY_ID_FAILURE";

export const REPLY_STARWEET_REQUEST = "REPLY_STARWEET_REQUEST";
export const REPLY_STARWEET__SUCCESS = "REPLY_STARWEET_SUCCESS";
export const REPLY_STARWEET_FAILURE = "REPLY_STARWEET_FAILURE";
